0.2.64

diff --git a/scripts/groot_build b/scripts/groot_build
--- a/scripts/groot_build
+++ b/scripts/groot_build
@@ -1,70 +1,94 @@
 #!/bin/bash
 
-if [ "$1" == "--help" ]; then
-  echo ""
-  echo "This builds an already download groot workspace in /opt/groot."
-  echo ""
-  echo "    Options:"
-  echo "        --help      : this help message"
-  echo "        --pre-clean : pre-clean each workspace"
-  echo ""
-  echo "    Current sources:"
-  echo "        ecto"
-  echo "        ecl"
-  echo "        navi"
-  echo "        dslam"
-  echo "        gopher"
-  echo ""
-  exit 0
-fi
+#!/usr/bin/env bash
+
+###########################
+# Command Line
+###########################
+
+for i in "$@"
+do
+case $i in
+    --help)
+    SHOW_HELP=1
+    shift
+    ;;
+    --install)
+    INSTALL="--install"
+    shift
+    ;;
+    --rosdeps)
+    ROSDEPS=1
+    shift
+    ;;
+    --pre-clean)
+    PRECLEAN="--pre-clean"
+    shift
+    ;;
+    *)
+       # unknown option
+    ;;
+esac
+done
+
 ###########################
 # Variables
 ###########################
 
 GROOT=/opt/groot
 
-if [ ! -d "${GROOT}/gopher_ws" ]; then
-  echo "No groot workspace found, try 'groot_sources' to build one."
-  exit 1
-else
-  GROOT_EXISTS=1
-fi
-
 if [ ! -z "${ROS_MASTER_URI}" ]; then
   echo "This is a ros environment, you must run this script from a non-ros environment (new shell)."
   exit 1
 fi
 
-if [ "$1" == "--pre-clean" ]; then
-  PRECLEAN="--pre-clean"
-else
-  PRECLEAN=""
-fi
-
-REPOS=("ecto" "ecl" "navi" "dslam" "gopher")
+REPOS=("ecto" "ecl" "navi" "rocon" "dslam" "gopher")
+DISCOVERED_REPOS=()
+for repo in ${REPOS[*]}; do
+  if [ -d "${GROOT}/${repo}_ws" ]; then
+    DISCOVERED_REPOS+=(${repo})
+  fi
+done
 
 ###########################
 # Functions
 ###########################
 
-check_rosdeps ()
+show_help ()
 {
-  echo "Checking for rosdeps."
-  for repo in ${REPOS[*]}; do
-    echo "  Building ${repo}."
-    cd ${GROOT}/${repo}_ws
-    yujin_make --install-rosdeps
-  done
+  echo ""
+  echo "This builds an all sources in /opt/groot."
+  echo ""
+  echo "    Usage:"
+  echo "        groot_build <options>"
+  echo ""
+  echo "    Options:"
+  echo "        --help      : this help message."
+  echo "        --pre-clean : pre-clean each workspace."
+  echo "        --rosdeps   : install workspace rosdeps only."
+  echo "        --install   : pass --install along with the build."
+  echo ""
+  exit 0
 }
-
 
 build_sources ()
 {
-  echo "Downloading groot."
-  for repo in ${REPOS[*]}; do
+  echo "Building groot."
+  for repo in ${DISCOVERED_REPOS[*]}; do
     echo "  Building ${repo}."
     cd ${GROOT}/${repo}_ws
-    yujin_make
+    if [ ! -z "$ROSDEPS" ]; then
+      yujin_make --install-rosdeps
+      if [ "$?" == "1" ]; then
+	echo "Error getting rosdeps for ${repo}, aborting."
+	exit 1
+      fi
+    fi
+    yujin_make ${PRECLEAN} ${INSTALL}
+    if [ "$?" == "1" ]; then
+      echo "Error building ${repo}, aborting."
+      exit 1
+    fi
   done
 }
 
@@ -72,8 +96,8 @@ build_sources ()
 # Work 
 ###########################
 
-if [ "$1" == "--rosdeps" ]; then
-  check_rosdeps
+if [ ! -z "$SHOW_HELP" ]; then
+  show_help
   exit 0
 fi
 
diff --git a/scripts/groot_sources b/scripts/groot_sources
--- a/scripts/groot_sources
+++ b/scripts/groot_sources
@@ -1,59 +1,126 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-if [ "$1" == "--help" ]; then
-  echo ""
-  echo "This downloads or updates the groot sources into /opt/groot."
-  echo ""
-  echo "    Options:"
-  echo "        --help      : this help message"
-  echo "        --delete    : delete before starting"
-  echo "        --update    : run wstool update on each workspace"
-  echo "        --status    : run wstool status on each workspace"
-  echo "        --branches  : show what branches are used in each workspace"
-  echo ""
-  echo "    Current sources:"
-  echo "        ecto"
-  echo "        ecl"
-  echo "        navi"
-  echo "        dslam"
-  echo "        gopher"
-  echo ""
-  exit 0
-fi
+###########################
+# Command Line
+###########################
+
+for i in "$@"
+do
+case $i in
+    --help)
+    SHOW_HELP=1
+    shift
+    ;;
+    --delete)
+    DELETE=1
+    shift
+    ;;
+    --install)
+    INSTALL_STRING="--install=/opt/yujin/indigo"
+    shift
+    ;;
+    --update)
+    UPDATE=1
+    shift
+    ;;
+    --list)
+    SHOW_REPOS=1
+    shift
+    ;;
+    --status)
+    SHOW_STATUS=1
+    shift
+    ;;
+    --branches)
+    SHOW_BRANCHES=1
+    shift
+    ;;
+    *)
+       # unknown option
+    ;;
+esac
+done
+
 ###########################
 # Variables
 ###########################
 
 GROOT=/opt/groot
 
-if [ -d "${GROOT}" ]; then
-  GROOT_EXISTS=1
+ALL_REPOS=("ecto" "ecl" "navi" "rocon" "dslam" "gopher")
+declare -A ALL_REPO_KEYS
+declare -A ALL_UNDERLAYS
+ALL_REPO_KEYS=( ["ecto"]="ecto" ["ecl"]="ecl" ["rocon"]="rocon" ["navi"]="yujin_navigation" ["dslam"]="dslam_desktop" ["gopher"]="gopher" )
+ALL_UNDERLAYS=( ["ecto"]="" ["ecl"]="" ["navi"]="" ["rocon"]="" ["dslam"]="${GROOT}/ecl/devel;${GROOT}/ecto/devel" ["gopher"]="${GROOT}/dslam/devel;${GROOT}/ecl/devel;${GROOT}/navi/devel;${GROOT}/rocon/devel;${GROOT}/ecto/devel" )
+
+REPOS=()
+
+if [ "$#" -gt 0 ]; then
+  for var in "$@"
+  do
+    REPOS+=($var)
+  done
+else
+  for repo in "${ALL_REPOS[@]}"
+  do
+    REPOS+=($repo)
+  done
 fi
-
-REPOS=("ecto" "ecl" "navi" "dslam" "gopher")
-REPO_KEYS=("ecto" "ecl" "yujin_navigation" "dslam_desktop" "gopher")
-
-UNDERLAYS=""
-for repo in ${REPOS[*]}; do
-  UNDERLAYS="${GROOT}/${repo}_ws/devel;${UNDERLAYS}"
-done
 
 ###########################
 # Functions
 ###########################
 
+show_help ()
+{
+  echo ""
+  echo "This downloads or updates the groot sources into /opt/groot."
+  echo ""
+  echo "    Usage:"
+  echo "        groot_sources <options>"
+  echo "        groot_sources <options> <space separated list of repos>"
+  echo ""
+  echo "    Repos: ecto ecl navi rocon dslam gopher"
+  echo ""
+  echo "    Options:"
+  echo "        --help      : this help message"
+  echo "        --list      : list repo details"
+  echo "        --delete    : delete workspaces"
+  echo "        --update    : run wstool update on each workspace"
+  echo "        --status    : run wstool status on each workspace"
+  echo "        --branches  : show what branches are used in each workspace"
+  echo ""
+  echo "    Admin Options:"
+  echo "        --install   : set the install location to /opt/yujin/indigo for all workspaces"
+  echo ""
+  exit 0
+}
+
+show_repos ()
+{
+  for repo in "${ALL_REPOS[@]}"
+  do
+    echo "${repo}"
+    echo "  rosinstall key: ${ALL_REPO_KEYS[${repo}]}"
+    echo "  underlays     : ${ALL_UNDERLAYS[${repo}]};/opt/yujin/indigo"
+  done
+}
+
 download_sources ()
 {
   echo "Downloading groot."
-  for ((i=0;i<${#REPOS[@]};++i)); do
-    repo=${REPOS[i]}
-    repo_key=${REPO_KEYS[i]}
+  for repo in "${REPOS[@]}"; do
+  #for ((i=0;i<${#REPOS[@]};++i)); do
     cd ${GROOT}
-    echo "  Downloading ${repo}."
-    yujin_init_workspace -j5 ${repo}_ws ${repo_key}
-    cd ${GROOT}/${repo}_ws
-    echo "  Configuring ${repo}."
-    yujin_init_build --underlays="${UNDERLAYS}" .
+    if [ -d "${GROOT}/${repo}_ws" ]; then
+      echo "  Workspace ${GROOT}/${repo}_ws already exists, skipping, remove manually or use --delete."
+    else
+      echo "  Downloading ${repo}."
+      yujin_init_workspace -j5 ${repo}_ws ${ALL_REPO_KEYS[${repo}]}
+      cd ${GROOT}/${repo}_ws
+      echo "  Configuring ${repo}."
+      yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/indigo" ${INSTALL_STRING} .
+    fi
   done
 }
 
@@ -70,7 +137,7 @@ update_sources ()
       yujin_init_workspace -j5 ${repo}_ws ${repo_key}
       cd ${GROOT}/${repo}_ws
       echo "  Configuring ${repo}."
-      yujin_init_build --underlays="${UNDERLAYS}" .
+      yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/indigo" .
     fi
     cd ${GROOT}/${repo}_ws/src
     echo "  Updating ${repo}."
@@ -100,49 +167,68 @@ show_status ()
 
 mkdir_groot ()
 {
-  mkdir ${GROOT}
-  if [ "$?" == "1" ]; then
-    echo "Could not create the groot directory (check permissions)."
-    exit 1
+  if [ ! -d "${GROOT}" ]; then
+    mkdir ${GROOT}
+    if [ "$?" == "1" ]; then
+      echo "Could not create the groot directory (check permissions)."
+      exit 1
+    fi
   fi
+}
+
+delete_sources ()
+{
+  echo "Deleting workspaces."
+  for repo in "${REPOS[@]}"; do
+    if [ -d "${GROOT}/${repo}_ws" ]; then
+      echo "  Deleting ${GROOT}/${repo}_ws."
+      rm -rf ${GROOT}/${repo}_ws
+    fi
+  done
 }
 
 ###########################
 # Workers
 ###########################
 
-if [ "$1" == "--delete" ]; then
-  rm -rf ${GROOT} 
-  mkdir_groot
-  download_sources
+if [ ! -z "$SHOW_HELP" ]; then
+  show_help
   exit 0
 fi
 
-if [ "$1" == "--status" ]; then
-  show_status
+if [ ! -z "$SHOW_REPOS" ]; then
+  show_repos
   exit 0
 fi
 
-if [ "$1" == "--branches" ]; then
-  show_branches
-  exit 0
-fi
-
-
-if [ "$1" == "--update" ]; then
-  if [ -z "$GROOT_EXISTS" ]; then
-    echo "No groot workspace found, run without --update first."
-    exit 1
+if [ ! -z "$SHOW_STATUS" ]; then
+  if [ ! -d "${GROOT}" ]; then
+    echo "No groot workspaces found."
+  else
+    show_status
   fi
+  exit 0
+fi
+
+if [ ! -z "$SHOW_BRANCHES" ]; then
+  if [ ! -d "${GROOT}" ]; then
+    echo "No groot workspaces found."
+  else
+    show_branches
+  fi
+  exit 0
+fi
+
+if [ ! -z "$DELETE" ]; then
+  delete_sources
+  exit 0
+fi
+
+if [ ! -z "${UPDATE}" ]; then
   update_sources
   exit 0
 fi
 
-# else, no options, just check and download
-if [ ! -z "${GROOT_EXISTS}" ]; then
-  echo "Groot exists, try with --delete."
-  exit 1
-fi
 mkdir_groot
 download_sources
 
