split groot docs yamls up for stable, devel, also updates to groot scripts

diff --git a/scripts/groot_binaries b/scripts/groot_binaries
--- a/scripts/groot_binaries
+++ b/scripts/groot_binaries
@@ -19,6 +19,14 @@ case $i in
     EXTERNAL=1
     shift
     ;;
+    --stable)
+    STABLE=1
+    shift
+    ;;
+    --devel)
+    DEVEL=1
+    shift
+    ;;
     --push)
     PUSH=1
     shift
@@ -47,6 +55,8 @@ show_help ()
   echo "        --help            : this help message"
   echo "        --external        : use the external server instead of the internal one"
   echo "        --install-rosdeps : install all rosdeps required by the groot binary installspace"
+  echo "        --stable          : work with the stable binaries"
+  echo "        --devel           : work with the devel binaries"
   echo ""
   echo "    Admin Options:"
   echo "        --push            : push local /opt/yujin/indigo installspace with the server"
@@ -54,13 +64,34 @@ show_help ()
   exit 0
 }
 
+###########################
+# Aborts
+###########################
+
+if [ -z "$STABLE" ] && [ -z "$DEVEL" ]; then
+  echo ""
+  echo "ERROR : you must set one of either --stable or --devel"
+  echo ""
+  exit 1
+fi
+
 if [ ! -z "$SHOW_HELP" ]; then
   show_help
   exit 0
 fi
 
+###########################
+# Variables
+###########################
+
+if [ ! -z "$STABLE" ]; then
+  RELEASE="stable"
+else
+  RELEASE="devel"
+fi
+
 # put the <rosdistro> folder here, should eventually move it to /opt/yujin/amd64
-export local_dir=/opt/yujin
+export local_dir=/opt/yujin/amd64
 
 if [ ! -z "$EXTERNAL" ]; then
   export remote_url=files@files.yujinrobot.com
@@ -82,10 +113,10 @@ export OPTIONS="--delete --recursive --links --verbose --compress"
 
 if [ ! -z "$INSTALL_ROSDEPS" ]; then
     echo ""
-    echo "Installing all rosdeps required by the binaries installspace in ${local_dir}/indigo"
+    echo "Installing all rosdeps required by the binaries installspace in ${local_dir}/indigo-${RELEASE}"
     echo ""
     source ${local_dir}/indigo/setup.bash
-    rosdep install -r --default-yes --from-paths ${local_dir}/indigo --ignore-src
+    rosdep install -r --default-yes --from-paths ${local_dir}/indigo-${RELEASE} --ignore-src
     exit 0   
 fi
 
@@ -96,12 +127,12 @@ if [ ! -z "$PUSH" ]; then
     #echo "Do you really want to push changes (if you aren't sure, you definitely do not)?[y/N]:"
     #read answer
     #if [ "$answer" == "y" ]; then
-        rsync ${OPTIONS} ${local_dir}/indigo ${remote_dir}
+        rsync ${OPTIONS} ${local_dir}/indigo-${RELEASE} ${remote_dir}
     #else
     #    echo "Aborting."
     #fi
     echo ""
 else
-    rsync ${OPTIONS} ${remote_dir}/indigo ${local_dir}
+    rsync ${OPTIONS} ${remote_dir}/indigo-${RELEASE} ${local_dir}
 fi
 
diff --git a/scripts/groot_sources b/scripts/groot_sources
--- a/scripts/groot_sources
+++ b/scripts/groot_sources
@@ -2,13 +2,43 @@
 
 
 ###########################
-# Functions
+# Global Functions
 ###########################
 
 function contains () {
   local e
   for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
   return 1
+}
+
+show_help ()
+{
+  echo ""
+  echo "This downloads or updates the groot sources into /opt/groot."
+  echo ""
+  echo "    Usage:"
+  echo "        groot_sources <--stable||--devel> <options>"
+  echo "        groot_sources <--stable||--devel> <options> <space separated list of repos>"
+  echo ""
+  echo "    Repos: ecto ecl dslam navi bootstrap gopher concert desktop"
+  echo ""
+  echo "    Required Option (one of):"
+  echo "        --stable                                        : work with the stable sources/binaries"
+  echo "        --devel                                         : work with the devel sources/binaries"
+  echo ""
+  echo "    Options:"
+  echo "        --help                                          : show this help message"
+  echo "        --list                                          : list repo details"
+  echo "        --delete                                        : delete workspaces"
+  echo "        --update                                        : run wstool update on each workspace"
+  echo "        --status                                        : run wstool status on each workspace"
+  echo "        --branches                                      : show what branches are used in each workspace"
+  echo "        --source-directory=<directory> | -d=<directory> : specify custom source directory"
+  echo ""
+  echo "    Admin Options:"
+  echo "        --install   : set the install location to /opt/yujin/indigo for all workspaces"
+  echo ""
+  exit 0
 }
 
 ###########################
@@ -46,6 +76,14 @@ case $i in
     SHOW_BRANCHES=1
     shift
     ;;
+    --stable)
+    STABLE=1
+    shift
+    ;;
+    --devel)
+    DEVEL=1
+    shift
+    ;;
     -d=*|--source-directory=*)
     USE_CUSTOM_SOURCE_DIRECTORY=1
     CUSTOM_SOURCE_DIRECTORY="${i#*=}"
@@ -58,12 +96,37 @@ esac
 done
 
 ###########################
+# Early Aborts
+###########################
+
+if [ ! -z "$SHOW_HELP" ]; then
+  show_help
+  exit 0
+fi
+
+if [ ! -z "${ROS_MASTER_URI}" ]; then
+  echo "    This is a ros environment, you must run this script from a non-ros environment (new shell)."
+  exit 1
+fi
+
+if [ -z "$STABLE" ] && [ -z "$DEVEL" ]; then
+  echo ""
+  echo "    You must set one of either --stable or --devel."
+  echo "        Run with --help for more information."
+  echo ""
+  exit 1
+fi
+
+###########################
 # Variables
 ###########################
 
-if [ ! -z "${ROS_MASTER_URI}" ]; then
-  echo "This is a ros environment, you must run this script from a non-ros environment (new shell)."
-  exit 1
+if [ ! -z "$STABLE" ]; then
+  RELEASE="stable"
+  WS="stable_ws"
+else
+  RELEASE="devel"
+  WS="ws"
 fi
 
 if [ ! -z "$USE_CUSTOM_SOURCE_DIRECTORY" ]; then
@@ -76,13 +139,13 @@ ALL_REPOS=("ecto" "ecl" "dslam" "navi" "bootstrap" "gopher" "concert" "desktop")
 declare -A ALL_REPO_KEYS
 declare -A ALL_UNDERLAYS
 
-ALL_REPO_KEYS=( ["ecto"]="ecto-devel" ["ecl"]="ecl-devel" ["bootstrap"]="gopher_bootstrap-devel" ["concert"]="gopher_concert-devel" ["navi"]="gopher_navigation-devel" ["dslam"]="gopher_dslam-devel" ["gopher"]="gopher-devel" ["desktop"]="gopher_desktop-devel" )
+ALL_REPO_KEYS=( ["ecto"]="ecto-${RELEASE}" ["ecl"]="ecl-${RELEASE}" ["bootstrap"]="gopher_bootstrap-${RELEASE}" ["concert"]="gopher_concert-${RELEASE}" ["navi"]="gopher_navigation-${RELEASE}" ["dslam"]="gopher_dslam-${RELEASE}" ["gopher"]="gopher-${RELEASE}" ["desktop"]="gopher_desktop-${RELEASE}" )
 
-E_CLOUD="${GROOT}/ecl_ws/devel;${GROOT}/ecto_ws/devel"
-DSLAM_CLOUD="${GROOT}/dslam_ws/devel;${E_CLOUD}"
-NAVI_CLOUD="${GROOT}/navi_ws/devel;${DSLAM_CLOUD}"
-BOOTSTRAP_CLOUD="${GROOT}/bootstrap_ws/devel;${NAVI_CLOUD}"
-SOFTWARE_CLOUD="${GROOT}/concert_ws/devel;${BOOTSTRAP_CLOUD}"
+E_CLOUD="${GROOT}/ecl_${WS}/devel;${GROOT}/ecto_${WS}/devel"
+DSLAM_CLOUD="${GROOT}/dslam_${WS}/devel;${E_CLOUD}"
+NAVI_CLOUD="${GROOT}/navi_${WS}/devel;${DSLAM_CLOUD}"
+BOOTSTRAP_CLOUD="${GROOT}/bootstrap_${WS}/devel;${NAVI_CLOUD}"
+SOFTWARE_CLOUD="${GROOT}/concert_${WS}/devel;${BOOTSTRAP_CLOUD}"
 
 ALL_UNDERLAYS=( ["ecto"]="" ["ecl"]="" ["dslam"]="${E_CLOUD}" ["navi"]="${DSLAM_CLOUD}" ["bootstrap"]="${NAVI_CLOUD}" ["concert"]="${BOOTSTRAP_CLOUD}" ["gopher"]="${BOOTSTRAP_CLOUD}" ["desktop"]="${SOFTWARE_CLOUD}")
 
@@ -104,32 +167,6 @@ fi
 # Functions
 ###########################
 
-show_help ()
-{
-  echo ""
-  echo "This downloads or updates the groot sources into /opt/groot."
-  echo ""
-  echo "    Usage:"
-  echo "        groot_sources <options>"
-  echo "        groot_sources <options> <space separated list of repos>"
-  echo ""
-  echo "    Repos: ecto ecl dslam navi bootstrap gopher concert desktop"
-  echo ""
-  echo "    Options:"
-  echo "        --help                                          : show this help message"
-  echo "        --list                                          : list repo details"
-  echo "        --delete                                        : delete workspaces"
-  echo "        --update                                        : run wstool update on each workspace"
-  echo "        --status                                        : run wstool status on each workspace"
-  echo "        --branches                                      : show what branches are used in each workspace"
-  echo "        --source-directory=<directory> | -d=<directory> : specify custom source directory"
-  echo ""
-  echo "    Admin Options:"
-  echo "        --install   : set the install location to /opt/yujin/indigo for all workspaces"
-  echo ""
-  exit 0
-}
-
 show_repos ()
 {
   for repo in "${ALL_REPOS[@]}"
@@ -147,14 +184,14 @@ download_sources ()
   #for ((i=0;i<${#REPOS[@]};++i)); do
     cd ${GROOT}
     if contains ${repo} ${ALL_REPOS[@]}; then
-      if [ -d "${GROOT}/${repo}_ws" ]; then
-	echo "  Workspace ${GROOT}/${repo}_ws already exists, skipping, remove manually or use --delete."
+      if [ -d "${GROOT}/${repo}_${WS}" ]; then
+	echo "  Workspace ${GROOT}/${repo}_${WS} already exists, skipping, remove manually or use --delete."
       else
 	echo "  Downloading ${repo}."
-	yujin_init_workspace -j5 ${repo}_ws ${ALL_REPO_KEYS[${repo}]}
-	cd ${GROOT}/${repo}_ws
+	yujin_init_workspace -j5 ${repo}_${WS} ${ALL_REPO_KEYS[${repo}]}
+	cd ${GROOT}/${repo}_${WS}
 	echo "  Configuring ${repo}."
-	yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/indigo" ${INSTALL_STRING} .
+	yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/amd64/indigo-${RELEASE}" ${INSTALL_STRING} .
       fi
     else
       echo ""
@@ -172,16 +209,16 @@ update_sources ()
     repo=${REPOS[i]}
     repo_key=${ALL_REPO_KEYS[${repo}]}
     if contains ${repo} ${ALL_REPOS[@]}; then
-      if [ ! -d "${GROOT}/${repo}_ws" ]; then
+      if [ ! -d "${GROOT}/${repo}_${WS}" ]; then
 	echo "${repo} not found, redownloading."
 	cd ${GROOT}
 	echo "  Downloading ${repo}."
-	yujin_init_workspace -j5 ${repo}_ws ${repo_key}
-	cd ${GROOT}/${repo}_ws
+	yujin_init_workspace -j5 ${repo}_${WS} ${repo_key}
+	cd ${GROOT}/${repo}_${WS}
 	echo "  Configuring ${repo}."
-	yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/indigo" .
+	yujin_init_build --underlays="${ALL_UNDERLAYS[${repo}]};/opt/yujin/amd64/indigo-${RELEASE}" .
       fi
-      cd ${GROOT}/${repo}_ws
+      cd ${GROOT}/${repo}_${WS}
       echo "  Updating ${repo} from ${repo_key}"
       echo ""
       echo "       yujin_init_workspace -j5 --merge ${repo_key}"
@@ -198,11 +235,17 @@ update_sources ()
 
 show_branches ()
 {
-  echo "Showing status of repos in groot."
+  echo "******************************************************"
+  echo "* Showing branch information of repositories in groot."
+  echo "******************************************************"
   for repo in ${REPOS[*]}; do
-    cd ${GROOT}/${repo}_ws/src
-    echo "************** Branches of ${repo} **************"
-    yujin_list_git_branches
+    if [ -d "${GROOT}/${repo}_${WS}/src" ]; then
+      cd ${GROOT}/${repo}_${WS}/src
+      echo "****************************"
+      echo "* ${repo}"
+      echo "****************************"
+      yujin_list_git_branches
+    fi
   done
 }
 
@@ -210,9 +253,11 @@ show_status ()
 {
   echo "Showing status of repos in groot."
   for repo in ${REPOS[*]}; do
-    echo "  Status of ${repo}."
-    cd ${GROOT}/${repo}_ws/src
-    wstool status
+    if [ -d "${GROOT}/${repo}_${WS}/src" ]; then
+      echo "  Status of ${repo}:"
+      cd ${GROOT}/${repo}_${WS}/src
+      wstool status
+    fi
   done
 }
 
@@ -231,9 +276,9 @@ delete_sources ()
 {
   echo "Deleting workspaces."
   for repo in "${REPOS[@]}"; do
-    if [ -d "${GROOT}/${repo}_ws" ]; then
-      echo "  Deleting ${GROOT}/${repo}_ws."
-      rm -rf ${GROOT}/${repo}_ws
+    if [ -d "${GROOT}/${repo}_${WS}" ]; then
+      echo "  Deleting ${GROOT}/${repo}_${WS}."
+      rm -rf ${GROOT}/${repo}_${WS}
     fi
   done
 }
@@ -241,11 +286,6 @@ delete_sources ()
 ###########################
 # Workers
 ###########################
-
-if [ ! -z "$SHOW_HELP" ]; then
-  show_help
-  exit 0
-fi
 
 if [ ! -z "$SHOW_REPOS" ]; then
   show_repos
